### ISSUE TITLE
[ERROR] The resource could not be found.

### ISSUE THREAD

**Issue by createitforme** [hermanho/MMM-OneDrive#10]
I am running the module on a docker install so I did a new install on another PI with out docker. 

After running MagicMirror on the non-docker PI I get the auth screen and am able to login. After that the terminal shows that the resource cannot be found.

Token.json is located in the correct folder and has been updated.

```
-rw-r--r-- 1 mirroradmin mirroradmin 1216 Nov 12 14:28 CachePlugin.js
-rw-r--r-- 1 mirroradmin mirroradmin 5060 Nov 12 14:28 AuthProvider.js
-rw-r--r-- 1 mirroradmin mirroradmin 1590 Nov 12 14:28 authConfig.js
-rw-r--r-- 1 mirroradmin mirroradmin 5462 Nov 12 14:31 token.json
```

```
[2024-11-12 14:31:43.733] [DEBUG] [ONEDRIVE:CORE] onAuthReady token responed 
[2024-11-12 14:31:44.137] [LOG]   [ONEDRIVE:CORE] onAuthReady done 
[2024-11-12 14:31:44.139] [LOG]   [ONEDRIVE:CORE] Getting Album info chunks. 
[2024-11-12 14:31:45.452] [ERROR] Trace: [ONEDRIVE:CORE] request fail with URL https://graph.microsoft.com/v1.0/me/drive/items/e69b16d18dabbef5!0:/SkyDriveCache/Albums:/children
    at OneDrivePhotos.logTrace (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/OneDrivePhotos.js:74:13)
    at OneDrivePhotos.request (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/OneDrivePhotos.js:112:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getAlbum (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/OneDrivePhotos.js:139:24)
    at async OneDrivePhotos.getAlbums (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/OneDrivePhotos.js:120:18)
    at async Class.getAlbums (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_helper.js:225:15)
    at async Class.getAlbumList (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_helper.js:270:18)
    at async Class.scanJob (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_helper.js:251:5) 
[2024-11-12 14:31:45.454] [ERROR] Trace: [ONEDRIVE:CORE] data null
    at OneDrivePhotos.logTrace (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/OneDrivePhotos.js:74:13)
    at OneDrivePhotos.request (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/OneDrivePhotos.js:113:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getAlbum (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/OneDrivePhotos.js:139:24)
    at async OneDrivePhotos.getAlbums (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/OneDrivePhotos.js:120:18)
    at async Class.getAlbums (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_helper.js:225:15)
    at async Class.getAlbumList (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_helper.js:270:18)
    at async Class.scanJob (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_helper.js:251:5) 
[2024-11-12 14:31:45.456] [ERROR] [ONEDRIVE:CORE] The resource could not be found.
stack:
Error: The resource could not be found.
    at new GraphError (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_modules/@microsoft/microsoft-graph-client/lib/src/GraphError.js:34:28)
    at GraphErrorHandler.constructErrorFromResponse (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_modules/@microsoft/microsoft-graph-client/lib/src/GraphErrorHandler.js:63:22)
    at Function.<anonymous> (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_modules/@microsoft/microsoft-graph-client/lib/src/GraphErrorHandler.js:91:48)
    at step (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_modules/tslib/tslib.js:195:27)
    at Object.next (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_modules/tslib/tslib.js:176:57)
    at /home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_modules/tslib/tslib.js:165:16)
    at GraphErrorHandler.getError (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_modules/@microsoft/microsoft-graph-client/lib/src/GraphErrorHandler.js:87:24)
    at GraphRequest.<anonymous> (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_modules/@microsoft/microsoft-graph-client/lib/src/GraphRequest.js:315:84)
    at step (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_modules/tslib/tslib.js:195:27)
    at Object.throw (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_modules/tslib/tslib.js:176:57)
    at rejected (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_modules/tslib/tslib.js:167:69)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 
[2024-11-12 14:31:45.456] [LOG]   [ONEDRIVE:CORE] Error: The resource could not be found. 
[2024-11-12 14:31:45.457] [ERROR] The resource could not be found.
stack:
Error: The resource could not be found.
    at new GraphError (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_modules/@microsoft/microsoft-graph-client/lib/src/GraphError.js:34:28)
    at GraphErrorHandler.constructErrorFromResponse (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_modules/@microsoft/microsoft-graph-client/lib/src/GraphErrorHandler.js:63:22)
    at Function.<anonymous> (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_modules/@microsoft/microsoft-graph-client/lib/src/GraphErrorHandler.js:91:48)
    at step (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_modules/tslib/tslib.js:195:27)
    at Object.next (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_modules/tslib/tslib.js:176:57)
    at /home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_modules/tslib/tslib.js:165:16)
    at GraphErrorHandler.getError (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_modules/@microsoft/microsoft-graph-client/lib/src/GraphErrorHandler.js:87:24)
    at GraphRequest.<anonymous> (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_modules/@microsoft/microsoft-graph-client/lib/src/GraphRequest.js:315:84)
    at step (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_modules/tslib/tslib.js:195:27)
    at Object.throw (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_modules/tslib/tslib.js:176:57)
    at rejected (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_modules/tslib/tslib.js:167:69)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 
[2024-11-12 14:31:45.461] [INFO]  Finish Album scanning. Properly scanned : 0 
[2024-11-12 14:31:45.462] [INFO]  Albums:  
[2024-11-12 14:31:45.464] [INFO]  getAlbumList done 
[2024-11-12 14:31:45.465] [WARN]  There is no album to get photos. 
[2024-11-12 14:31:45.469] [INFO]  Next scan will be at 2024-11-12T20:26:26.442Z 
[2024-11-12 14:32:45.475] [INFO]  Used last pic in list 
[2024-11-12 14:32:45.478] [ERROR] couldn't send  0  pics 
[2024-11-12 14:33:45.468] [INFO]  Used last pic in list 
[2024-11-12 14:33:45.469] [ERROR] couldn't send  0  pics 
```

**Comment by hermanho** [comment]
@createitforme Please switch to dev branch and try if it works.

**Comment by createitforme** [comment]
New errors this time.

```
[2024-11-12 21:40:37.228] [LOG]   [ONEDRIVE:CORE] onAuthReady token responed 
[2024-11-12 21:40:37.837] [LOG]   [ONEDRIVE:CORE] onAuthReady done 
[2024-11-12 21:40:37.837] [LOG]   [ONEDRIVE:CORE] Getting Album info chunks. 
[2024-11-12 21:40:39.483] [ERROR] [ONEDRIVE:CORE] [getAlbumThumbnail]request fail get URL: https://graph.microsoft.com/v1.0/drives/b!RHKBF5I1ZUSKsN7CtigeaXeMQ1t_5VZAuGAZNZFIovagg9MbeMhgSJT0-7mMv_mS/items/E69B16D18DABBEF5!s8de3edecbe7b459a89a0c1bd6bf1e0c2/thumbnails?$select=mediumSquare 
[2024-11-12 21:40:39.484] [ERROR] [ONEDRIVE:CORE] [getAlbumThumbnail]data:  null 
[2024-11-12 21:40:39.485] [ERROR] [ONEDRIVE:CORE] Invalid request
stack:
Error: Invalid request
    at new GraphError (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_modules/@microsoft/microsoft-graph-client/lib/src/GraphError.js:34:28)
    at GraphErrorHandler.constructErrorFromResponse (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_modules/@microsoft/microsoft-graph-client/lib/src/GraphErrorHandler.js:63:22)
    at Function.<anonymous> (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_modules/@microsoft/microsoft-graph-client/lib/src/GraphErrorHandler.js:91:48)
    at step (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_modules/tslib/tslib.js:195:27)
    at Object.next (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_modules/tslib/tslib.js:176:57)
    at /home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_modules/tslib/tslib.js:165:16)
    at GraphErrorHandler.getError (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_modules/@microsoft/microsoft-graph-client/lib/src/GraphErrorHandler.js:87:24)
    at GraphRequest.<anonymous> (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_modules/@microsoft/microsoft-graph-client/lib/src/GraphRequest.js:315:84)
    at step (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_modules/tslib/tslib.js:195:27)
    at Object.throw (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_modules/tslib/tslib.js:176:57)
    at rejected (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_modules/tslib/tslib.js:167:69)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 
[2024-11-12 21:40:39.486] [ERROR] [ONEDRIVE:CORE] Error in getAlbum() Error: Invalid request 
[2024-11-12 21:40:39.486] [ERROR] [ONEDRIVE:CORE] Error: Invalid request 
[2024-11-12 21:40:39.487] [ERROR] Invalid request
stack:
Error: Invalid request
    at new GraphError (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_modules/@microsoft/microsoft-graph-client/lib/src/GraphError.js:34:28)
    at GraphErrorHandler.constructErrorFromResponse (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_modules/@microsoft/microsoft-graph-client/lib/src/GraphErrorHandler.js:63:22)
    at Function.<anonymous> (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_modules/@microsoft/microsoft-graph-client/lib/src/GraphErrorHandler.js:91:48)
    at step (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_modules/tslib/tslib.js:195:27)
    at Object.next (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_modules/tslib/tslib.js:176:57)
    at /home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_modules/tslib/tslib.js:165:16)
    at GraphErrorHandler.getError (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_modules/@microsoft/microsoft-graph-client/lib/src/GraphErrorHandler.js:87:24)
    at GraphRequest.<anonymous> (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_modules/@microsoft/microsoft-graph-client/lib/src/GraphRequest.js:315:84)
    at step (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_modules/tslib/tslib.js:195:27)
    at Object.throw (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_modules/tslib/tslib.js:176:57)
    at rejected (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_modules/tslib/tslib.js:167:69)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 
```

**Comment by hermanho** [comment]
@createitforme  Please do some testings in Microsoft offical Graph Explorer

1. Go to https://developer.microsoft.com/en-us/graph/graph-explorer
2. Sign in at the top right concer
    ![Screenshot 2024-11-13 上午11 27 14](https://github.com/user-attachments/assets/a76b67a8-419f-4c0c-9ba5-2359aa8811c1)
3. Run query with the following url
    ```https://graph.microsoft.com/v1.0/me/drive/bundles?filter=bundle/album+ne+null```
4. You can see the response data in the bottom panel. Please **DON'T** paste the whole resposne in here because of sensitive data. 
    ```
    {
        "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users('###########')/drive/bundles",
        "@odata.count": 4,
        "@microsoft.graph.tips": "Use $select to choose only the properties your app needs, as this can lead to performance improvements. For example: GET me/drive/bundles?$select=audio,bundle",
        "value": [
        ...
        ]
    }
    ```
    Please can find with the keyword `E69B16D18DABBEF5!s8de3edecbe7b459a89a0c1bd6bf1e0c2`. Please remove **webUrl** and paste in here
    ```
    {
        "createdDateTime": "2024-01-10T14:44:18.583Z",
        "cTag": "adasdasdsad#",
        "eTag": "asdasdasdx",
        "id": "E69B16D18DABBEF5!s8de3edecbe7b459a89a0c1bd6bf1e0c2",
        "createdBy": ...
        "lastModifiedBy": ...
        "parentReference": {
            "driveId": "b!RHKBF5I1ZUSKsN7CtigeaXeMQ1t_5VZAuGAZNZFIovagg9MbeMhgSJT0-7mMv_mS",
            "driveType": "personal",
            "id": "asdasdsadas"
        },
        "fileSystemInfo": ...
        "bundle":  ...
    }
    ```

**Comment by createitforme** [comment]
My output does not look like yours. It also only worked after consenting to file permissions. I am using a personal account with my own domain might be the difference. Not a M365 account.

```
{
            "@odata.etag": "\"{8DE3EDEC-BE7B-459A-89A0-C1BD6BF1E0C2},3\"",
            "createdDateTime": "2024-11-12T19:09:30Z",
            "eTag": "asdasdasdx",
            "id": "E69B16D18DABBEF5!s8de3edecbe7b459a89a0c1bd6bf1e0c2",
            "lastModifiedDateTime": "2024-11-12T19:09:32Z",
            "name": "MagicMirror",
            "size": 343025,
            "webUrl": "...",
            "cTag": "asdasdasdx",
            "commentSettings": {
                "commentingDisabled": {
                    "isDisabled": false
                }
            },
```

**Comment by hermanho** [comment]
I see. I am using M365 Family plan so I am not sure if it is working in SharePoint. Will you get the success result with this url in graph explorer?

`https://graph.microsoft.com/v1.0/me/drives/b!RHKBF5I1ZUSKsN7CtigeaXeMQ1t_5VZAuGAZNZFIovagg9MbeMhgSJT0-7mMv_mS/items/E69B16D18DABBEF5!s8de3edecbe7b459a89a0c1bd6bf1e0c2/children`

These are the key fields in the response.
```
{
    "@odata.count": 2,
    "value": [
        {
            "@microsoft.graph.downloadUrl": "######",
            "id": "########",
            "lastModifiedDateTime": "2024-01-10T17:21:58.54Z",
            "name": "20200117_090301068_iOS.heic",
            "size": 1520961,
            "fileSystemInfo": {
                "createdDateTime": "2020-01-17T09:03:01.068Z",
                "lastModifiedDateTime": "2023-07-21T13:46:19.66Z"
            },
            "image": {
                "height": 3024,
                "width": 4032
            },
            "photo": {
                "cameraMake": "Apple",
                "cameraModel": "iPhone XR",
                "exposureDenominator": 50,
                "exposureNumerator": 1,
                "focalLength": 4.25,
                "fNumber": 1.8,
                "iso": 100,
                "orientation": 1,
                "takenDateTime": "2020-01-17T17:03:01Z"
            }
        }
    ]
}
```

**Comment by hermanho** [comment]
How do you create the 'MagicMirror" album? Is it from this screen? Are you the owner of the album or shared from someone? 

![](https://github.com/user-attachments/assets/a25c5620-f2fc-44c2-9202-a7b6b88797d6)


Could you please double check the value of parentReference.driveId and parentReference.driveType in previous payload? This driveId should be the same from `https://graph.microsoft.com/v1.0/me/drive`

**Comment by createitforme** [comment]
Sorry for the delay in responding. I have tried this every way I can think of. I tried it with my work account, but business accounts do not support photos for some reason. I've signed up for a M365 family account to match yours and I still get the same results.

I'm not sure what you have done differently in your account versus mine. Mine is vanilla with only one album created on the web just as the picture above.

**Comment by hermanho** [comment]
I created a new microsoft account with free plan and fixed the code. Would you pull the latest `dev` branch and try again?

**Comment by createitforme** [comment]
It works! Thank you!

Once I added more than one picture it throws cache errors in the logs, but it still rotates the images.

```
[2024-12-01 22:47:24.404] [WARN]  Cache Config does not exist: /home/mirroradmin/MagicMirror/modules/MMM-OneDrive/cache/config.json 
[2024-12-01 22:47:24.404] [ERROR] unable to write Cache Config 
[2024-12-01 22:47:24.405] [ERROR] Cannot set properties of null (setting 'CACHE_HASH')
stack:
TypeError: Cannot set properties of null (setting 'CACHE_HASH')
    at Class.saveCacheConfig (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_helper.js:453:19)
    at Class.getAlbums (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_helper.js:251:7)
    at Class.getAlbumList (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_helper.js:293:18)
    at Class.scanJob (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_helper.js:274:5)

[2024-12-01 22:47:24.407] [WARN]  Cache Config does not exist: /home/mirroradmin/MagicMirror/modules/MMM-OneDrive/cache/config.json 
[2024-12-01 22:47:24.411] [ERROR] unable to write Cache Config 
[2024-12-01 22:47:24.411] [ERROR] Cannot set properties of null (setting 'CACHE_ALBUMNS_PATH')
stack:
TypeError: Cannot set properties of null (setting 'CACHE_ALBUMNS_PATH')
    at Class.saveCacheConfig (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_helper.js:453:19)

[2024-12-01 22:47:25.426] [WARN]  Cache Config does not exist: /home/mirroradmin/MagicMirror/modules/MMM-OneDrive/cache/config.json 
[2024-12-01 22:47:25.426] [ERROR] unable to write Cache Config 
[2024-12-01 22:47:25.426] [ERROR] Cannot set properties of null (setting 'CACHE_PHOTOLIST_PATH')
stack:
TypeError: Cannot set properties of null (setting 'CACHE_PHOTOLIST_PATH')
    at Class.saveCacheConfig (/home/mirroradmin/MagicMirror/modules/MMM-OneDrive/node_helper.js:453:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by hermanho** [comment]
I updated the dev branch and it should be fine now.

**Comment by createitforme** [comment]
dev branch has zero errors and seems to be working perfectly. Thank you!

**Comment by hermanho** [comment]
The fixing has merged so you can switch back to main branch
