### ISSUE TITLE
can't get the popup to load for the Oauth token

### ISSUE THREAD

**Issue by decoorebp** [hermanho/MMM-OneDrive#7]
Hi,

I tried to make this module work on my MagicMirror but I'm not getting the described popup to authenticate the application with my OneDrive account.

Tried it on a PI5 running latest Pi-OS, NodeJS 20 LTS, MM 2.28

I couldn't find anything in the standard logs.

do you need more information?

**Comment by hermanho** [comment]
Please copy the logging from the terminal when you execute `npm start`

**Comment by Melkeraaen** [comment]
I have the same problem, is it another way to get authorized?

**Comment by hermanho** [comment]
@Melkeraaen you can follow the steps in here:

https://github.com/hermanho/MMM-OneDrive/blob/main/INSTALL.md#sperated-machine-when-the-device-does-not-have-desktop-ui

**Comment by blazedsonic** [comment]
I keep getting this error. I connect remotely to the desktop over VNC and execute the install. It appears its having issues opening the browser (chromium installed). 

```
[2025-01-21 20:51:06.746] [ERROR] [ONEDRIVE:AuthProvider] Unable to open external browser. Please run the module with a screen UI environment  TypeError: Cannot read properties of undefined (reading 'openExternal')
    at openBrowser (/root/MagicMirror/modules/MMM-OneDrive/msal/AuthProvider.js:102:21)
    at PublicClientApplication.acquireTokenInteractive (/root/MagicMirror/modules/MMM-OneDrive/node_modules/@azure/msal-node/lib/msal-node.cjs:11060:19)
    at async AuthProvider.getTokenInteractive (/root/MagicMirror/modules/MMM-OneDrive/msal/AuthProvider.js:109:26)
    at async AuthProvider.getToken (/root/MagicMirror/modules/MMM-OneDrive/msal/AuthProvider.js:69:22)
    at async Auth.<anonymous> (/root/MagicMirror/modules/MMM-OneDrive/OneDrivePhotos.js:87:33) 
[2025-01-21 20:51:06.748] [ERROR] [ONEDRIVE:CORE] onAuthReady error TypeError: Cannot read properties of undefined (reading 'openExternal')
    at openBrowser (/root/MagicMirror/modules/MMM-OneDrive/msal/AuthProvider.js:102:21)
    at PublicClientApplication.acquireTokenInteractive (/root/MagicMirror/modules/MMM-OneDrive/node_modules/@azure/msal-node/lib/msal-node.cjs:11060:19)
    at async AuthProvider.getTokenInteractive (/root/MagicMirror/modules/MMM-OneDrive/msal/AuthProvider.js:109:26)
    at async AuthProvider.getToken (/root/MagicMirror/modules/MMM-OneDrive/msal/AuthProvider.js:69:22)
    at async Auth.<anonymous> (/root/MagicMirror/modules/MMM-OneDrive/OneDrivePhotos.js:87:33) 
[2025-01-21 20:51:06.749] [ERROR] Cannot read properties of undefined (reading 'openExternal')
stack:
TypeError: Cannot read properties of undefined (reading 'openExternal')
    at openBrowser (/root/MagicMirror/modules/MMM-OneDrive/msal/AuthProvider.js:102:21)
    at PublicClientApplication.acquireTokenInteractive (/root/MagicMirror/modules/MMM-OneDrive/node_modules/@azure/msal-node/lib/msal-node.cjs:11060:19)
    at async AuthProvider.getTokenInteractive (/root/MagicMirror/modules/MMM-OneDrive/msal/AuthProvider.js:109:26)
    at async AuthProvider.getToken (/root/MagicMirror/modules/MMM-OneDrive/msal/AuthProvider.js:69:22)
    at async Auth.<anonymous> (/root/MagicMirror/modules/MMM-OneDrive/OneDrivePhotos.js:87:33) 
[2025-01-21 20:51:06.751] [ERROR] Whoops! There was an uncaught exception... 
[2025-01-21 20:51:06.751] [ERROR] TypeError: Cannot read properties of undefined (reading 'filter')
    at Class.getAlbumList (/root/MagicMirror/modules/MMM-OneDrive/node_helper.js:299:30)
    at async Class.scanJob (/root/MagicMirror/modules/MMM-OneDrive/node_helper.js:274:5) 
[2025-01-21 20:51:06.752] [ERROR] MagicMirror² will not quit, but it might be a good idea to check why this happened. Maybe no internet connection? 
[2025-01-21 20:51:06.752] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MagicMirrorOrg/MagicMirror/issues 
```

**Comment by hermanho** [comment]
@blazedsonic Please copy the system information from the terminal / logging.
Example:
```
[2025-01-22 xxxxxx] [INFO]  System information:
### SYSTEM:   manufacturer: Apple Inc.; model: Mac; raspberry: undefined; virtual: false
### OS:       platform: darwin; distro: macOS; release: 111; arch: arm64; kernel: 2222
### VERSIONS: electron: 1111; used node: 2222; installed node: 3333; npm: 444; pm2: 5555
```

**Comment by CyruS1337** [comment]
I installed the module as described (https://github.com/hermanho/MMM-OneDrive/blob/main/INSTALL.md). Do I now need to go to "www.onedrive.com" with my Raspberry Pi? Or how do I obtain this token from OneDrive? I do not understand the next steps and hope for your support

**Comment by hermanho** [comment]
@CyruS1337  a device code authorization is implemented. Please pull from the latest commit and you can follow the On-device section in https://github.com/hermanho/MMM-OneDrive/blob/main/INSTALL.md#on-device-ssh-or-vnc-with-desktop-ui

**Comment by CyruS1337** [comment]
@hermanho 

Thank you for the information. Sorry, but either I'm not getting it or I'm a noob. I connect via SSH to the Raspberry. Do I need to enter the commands in the SSH? If yes, I have done that, and what should I do afterwards?

**Comment by CyruS1337** [comment]
@hermanho  I have executed this command as per the installation and restarted. What do I have to do for it to be executed?

`cd ~/MagicMirror/modules
git clone https://github.com/hermanho/MMM-OneDrive.git
cd MMM-OneDrive
npm run install-prod`

**Comment by hermanho** [comment]
@CyruS1337 

```
cd ~/MagicMirror
npm run start
```

**Comment by CyruS1337** [comment]
It worked, thank you very much. I forgot to restart the Pi. I then added the following code to the config: 
`		{
			  module: "MMM-OneDrive",
			  position: "top_right",
			  config: {
				albums: ["Test"], // Set your album name. like ["My wedding", "family share", "Travle to Paris"]
				updateInterval: 1000 * 60, // minimum 10 seconds.
				sort: "new", // "old", "random"
				condition: {
				  fromDate: null, // Or "2018-03", RFC ... format available
				  toDate: null, // Or "2019-12-25",
				  minWidth: null, // Or 400
				  maxWidth: null, // Or 8000
				  minHeight: null, // Or 400
				  maxHeight: null, // Or 8000
				  minWHRatio: null,
				  maxWHRatio: null,
				  // WHRatio = Width/Height ratio ( ==1 : Squared Photo,   < 1 : Portraited Photo, > 1 : Landscaped Photo)
				},
				showWidth: 1080, // These values will be used for quality of downloaded photos to show. real size to show in your MagicMirror region is recommended.
				showHeight: 1920,
				timeFormat: "YYYY/MM/DD HH:mm", // Or `relative` can be used.
			  }
			},
`

Can I just create the folder 'Test' on my OneDrive on the 'main page'? Because it doesn't show me any photos.

**Comment by hermanho** [comment]
@CyruS1337  it is required a "album" under "Photos", not folder under "My files"

![Image](https://github.com/user-attachments/assets/b9b8523d-1e44-4a7b-8edd-05e22b35b8e2)

**Comment by CyruS1337** [comment]
@hermanho 

Great, it worked now. Thank you very much :)
